### ISSUE TITLE
Can't `go get` with go version `1.12`

### ISSUE THREAD

**Issue by mrmakeit** [monax/hoard#63]
Attempting to `go get github.com/monax/hoard/cmd/hoard`results in multiple import errors:
```
go/src/github.com/monax/hoard/server/server.go:9:2: code in directory /<redacted>/go/src/github.com/monax/hoard expects import "github.com/monax/hoard/v3"
go/src/github.com/monax/hoard/config/storage/filesystem.go:8:2: code in directory /<redacted>/go/src/github.com/monax/hoard/storage expects import "github.com/monax/hoard/v3/storage"
```

This is a brand new go install with $GOPATH set to `$HOME/go` which does exist.

Verbose Log: https://pastebin.com/23dCHDf9

**Comment by silasdavis** [comment]
We have switched to go modules. Currently there doesn't seem to be a massively user friendly way to get the old behaviour, but the following works:

```shell
GO111MODULE=on go get github.com/monax/hoard/cmd/hoard
```
See: https://github.com/golang/go/issues/27653

Also our recommended way to get a release is from: https://github.com/monax/hoard/releases where we have cross-compiled binaries that contain the correct version metadata and link to our actual releases. In the future we may use also use build tags to enable specific storage backends selectively so that will further demerit go get installs.

As an aside: nice to hear someone else is using Hoard. Feel free to open issues or feature requests.
